categories:
    path:     /
    defaults: { _controller: "SheikhuLibraryBundle:Categorie:index" }

categories_show:
    path:     /{id}/show
    defaults: { _controller: "SheikhuLibraryBundle:Categorie:show" }

categories_new:
    path:     /new
    defaults: { _controller: "SheikhuLibraryBundle:Categorie:new" }

categories_create:
    path:     /create
    defaults: { _controller: "SheikhuLibraryBundle:Categorie:create" }
    requirements: { _method: post }

categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "SheikhuLibraryBundle:Categorie:edit" }

categories_update:
    path:     /{id}/update
    defaults: { _controller: "SheikhuLibraryBundle:Categorie:update" }
    requirements: { _method: post|put }

categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "SheikhuLibraryBundle:Categorie:delete" }
    requirements: { _method: post|delete }
