prets:
    path:     /
    defaults: { _controller: "SheikhuLibraryBundle:Pret:index" }

prets_show:
    path:     /{id}/show
    defaults: { _controller: "SheikhuLibraryBundle:Pret:show" }

prets_new:
    path:     /{code}/new
    defaults: { _controller: "SheikhuLibraryBundle:Pret:new" }

prets_create:
    path:     /{code}/create
    defaults: { _controller: "SheikhuLibraryBundle:Pret:create" }
    requirements: { _method: post }

prets_edit:
    path:     /{id}/edit
    defaults: { _controller: "SheikhuLibraryBundle:Pret:edit" }

prets_update:
    path:     /{id}/update
    defaults: { _controller: "SheikhuLibraryBundle:Pret:update" }
    requirements: { _method: post|put }

prets_delete:
    path:     /{id}/delete
    defaults: { _controller: "SheikhuLibraryBundle:Pret:delete" }
    requirements: { _method: post|delete }

prets_retour:
    path:   /retour/{id}
    defaults: { _controller: "SheikhuLibraryBundle:Pret:retour" }
    requirements: { _method: get }