<?php

namespace Sheikhu\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends EntityRepository
{
    public function count()
    {
        return $this->createQueryBuilder('l')
            ->select("count(l)")
            ->getQuery()->getSingleScalarResult();
    }
}
