sheikhu_library_categories:
    resource: "@SheikhuLibraryBundle/Resources/config/routing/categorie.yml"
    prefix:   /categories

sheikhu_library_homepage:
    path:     /hello/{name}
    defaults: { _controller: SheikhuLibraryBundle:Default:index }
