sheikhu_library_livres:
    resource: "@SheikhuLibraryBundle/Resources/config/routing/livre.yml"
    prefix:   /livres

sheikhu_library_categories:
    resource: "@SheikhuLibraryBundle/Resources/config/routing/categorie.yml"
    prefix:   /categories

home:
    path:     /
    defaults: { _controller: SheikhuLibraryBundle:Default:index }
